applications:
  gnomoanalytics:
    facility: example_facility
    name: gnomoanalytics
    version: 69
data_publication_types:
  curated:
    description: Curated data publication
    facility: example_facility
    name: curated
  raw:
    description: Open access raw data
    facility: example_facility
    name: raw
data_publications:
  data_pub1:
    dataset:
      complete: true
      datafiles:
      - datafileCreateTime: 2012-08-01 00:52:23+02:00
        datafileModTime: 2012-08-01 00:52:23+02:00
        fileSize: 264188
        format: hdf5
        name: A000027.hdf5
      endDate: 2012-08-01 00:52:23+02:00
      investigation: 12100409-ST
      name: pub-00027
      startDate: 2012-07-31 22:20:37+02:00
      type: other
    dates:
    - date: '2012-08-01'
      dateType: Created
    - date: '2022-04-29'
      dateType: Submitted
    description: >-
      We provide the first 65535 integers from sequence A000027 of the
      On-Line Encyclopedia of Integer Sequences. The data consists of an
      HDF5 file, having one single entry: a one dimensional integer
      array.
    facility: example_facility
    fundingReferences:
    - fund1
    pid: DOI:00.0815/pub-00027
    publicationDate: 2022-10-31
    relatedItems:
    - fullReference: >-
        OEIS Foundation Inc. (2022), The positive integers, Entry
        A000027 in The On-Line Encyclopedia of Integer Sequences
      identifier: URL:http://oeis.org/A000027
      relatedItemType: Other
      relationType: References
      title: The positive integers
    subject: integer sequence; OEIS; On-Line Encyclopedia of Integer Sequences
    title: Data from OEIS sequence A000027
    type: curated
    users:
    - affiliations:
      - fullReference: "Universit\xE9 de Nancy"
        name: '01: Nancy'
      - fullReference: University of Chicago
        name: '02: Chicago'
        pid: ROR:024mw5h28
      contributorType: Creator
      email: nbour@example.org
      familyName: Bourbaki
      fullName: Bourbaki, Nicolas
      givenName: Nicolas
      orderKey: '01'
      user: nbour
datafile_formats:
  csv:
    description: Comma separated values
    facility: example_facility
    name: CSV
    type: text/csv
    version: N/A
  hdf5:
    description: Hierarchical Data Format version 5
    facility: example_facility
    name: HDF5
    type: application/x-hdf5
    version: N/A
  nexus:
    description: A common data format for neutron, x-ray and muon science
    facility: example_facility
    name: NeXus
    type: application/x-hdf5
    version: N/A
  text:
    description: Plain text file
    facility: example_facility
    name: Text
    type: text/plain
    version: N/A
  xml:
    description: XML document text
    facility: example_facility
    name: XML
    type: application/xml
    version: N/A
  other:
    description: Unknown file format
    facility: example_facility
    name: other
    version: N/A
dataset_types:
  raw:
    description: data collected from experiments on instruments
    facility: example_facility
    name: raw
  analyzed:
    description: data arising from the analysis of other data
    facility: example_facility
    name: analyzed
  other:
    description: data not belonging to any other category
    facility: example_facility
    name: other
facilities:
  example_facility:
    description: ESNF is an example facility
    fullName: Example Synchrotron and Neutron Facility
    name: ESNF
    url: http://www.esnf.example.org/
facility_cycles:
- cycles:
  - [2, 15, 8, 15]
  - [8, 15, 2, 15]
  endYear: 17
  facility: example_facility
  startYear: 7
fundings:
  fund1:
    awardNumber: AIS3241330750
    funderIdentifier: Crossref Funder ID:10.13039/100005376
    funderName: American Mathematical Society
instruments:
  e2:
    description: >
      A 3-dimensional part of the reciprocal space can be scanned in
      less then five steps by combining the "off-plane
      Bragg-scattering" and the flat-cone layer concept while using a
      new computer-controlled tilting axis of the detector bank.
    facility: example_facility
    fullName: E2 - Flat-Cone Diffractometer
    instrumentscientist: acord
    name: E2
    pid: DOI:00.0815/inst-00001
    technique: ndiff
    type: null
  eddi:
    description: >
      The experimental station EDDI (Energy Dispersive Diffraction) is
      a fixed station at the 7T-MPW-EDDI beamline.  The beamline
      provides the direct white photon beam emitted by the 7T
      multipole wiggler and is operated in the energy-dispersive mode
      of diffraction.  For the experiments two diffractometers with
      Eularian cradle segments (GE Inspection Technologies) are at the
      disposal for light and heavy weight samples.  For the
      acquisition of the diffraction patterns as well as the
      fluorescence signals two Germanium solid state detectors
      (Canberra) are available.
    facility: example_facility
    fullName: EDDI - Energy Dispersive Diffraction
    instrumentscientist: acord
    name: EDDI
    pid: DOI:00.0815/inst-00048
    technique: null
    type: null
  hike:
    description: >
      The system is designed for hard X-ray high kinetic energy
      photoelectron spectroscopy (HAXPES or HIKE) experiments in the
      excitation energy range from 2 keV to 12 keV with an optimized
      recorded kinetic energy range from 150 eV to 10000 eV.  The
      typical experiments running on the HIKE end station are
      investigations of bulk electronic properties - core levels and
      valence band, buried interfaces and x-ray standing waves.
    facility: example_facility
    fullName: HIKE - High Kinetic Energy Photoelectron Spectroscopy
    instrumentscientist: acord
    name: HIKE
    pid: DOI:00.0815/inst-00027
    technique: haxpes
    type: null
investigation_types:
  calibration:
    description: null
    facility: example_facility
    name: Calibration
  commercial_experiment:
    description: null
    facility: example_facility
    name: Commercial experiment
  engineering:
    description: null
    facility: example_facility
    name: Engineering
  experiment:
    description: null
    facility: example_facility
    name: Experiment
  simulation:
    description: null
    facility: example_facility
    name: Simulation
investigations:
  08100122-EF:
    datasets:
    - complete: true
      datafiles:
      - checksum: ac69460a
        datafileCreateTime: '2008-06-18T09:31:11+02:00'
        datafileModTime: '2008-06-18T09:31:11+02:00'
        fileSize: 368369
        format: nexus
        name: e201215.nxs
        parameters:
        - dateTimeValue: '2008-06-18T09:31:11+02:00'
          type: lastaccess
      endDate: null
      name: e201215
      startDate: '2008-03-13T11:39:42+01:00'
      type: raw
    - complete: false
      datafiles: []
      endDate: null
      name: e201216
      startDate: '2008-03-20T08:20:00+01:00'
      type: raw
    doi: DOI:00.0815/inv-00122
    endDate: null
    facility: example_facility
    fundingReferences: []
    instrument: hike
    invcol:
    - nbour
    - rbeck
    invguest:
    - jdoe
    invpi: jbotu
    keywords:
    - Durol
    name: 08100122-EF
    parameters:
    - stringValue: photon
      type: probe
    sample:
      name: Durol SC
      pid: IGSN:ESNFHNS8AYEZ
      type: durol
    shifts:
    - comment: Beamtime at HIKE
      endDate: '2008-03-13T16:00:00+01:00'
      startDate: '2008-03-13T08:00:00+01:00'
    startDate: '2008-03-13T11:39:42+01:00'
    title: Durol single crystal
    type: experiment
    visitId: 1.1-P
  10100601-ST:
    datasets:
    - complete: true
      datafiles:
      - checksum: 81c44870
        datafileCreateTime: '2010-10-01T08:17:48+02:00'
        datafileModTime: '2010-10-01T08:17:48+02:00'
        fileSize: 446
        format: other
        name: e208339.dat
        parameters:
        - dateTimeValue: '2010-10-01T08:51:56+02:00'
          type: lastaccess
      - checksum: 8b369ddc
        datafileCreateTime: '2010-10-01T08:52:22+02:00'
        datafileModTime: '2010-10-01T08:52:22+02:00'
        fileSize: 73428
        format: nexus
        name: e208339.nxs
        parameters:
        - dateTimeValue: '2012-07-12T16:45:26+02:00'
          type: lastaccess
      endDate: '2010-10-01T08:17:48+02:00'
      name: e208339
      parameters:
      - numericValue: 5.0
        type: reactor_power
      - numericValue: 7.3
        type: magnetic_field
      startDate: '2010-09-30T12:27:24+02:00'
      type: raw
    - complete: true
      datafiles:
      - checksum: 284558f4
        datafileCreateTime: '2010-10-05T10:32:21+02:00'
        datafileModTime: '2010-10-05T10:32:21+02:00'
        fileSize: 394
        format: other
        name: e208341.dat
        parameters:
        - dateTimeValue: '2010-10-05T11:31:45+02:00'
          type: lastaccess
      - checksum: 7c72b4bc
        datafileCreateTime: '2010-10-05T11:31:53+02:00'
        datafileModTime: '2010-10-05T11:31:53+02:00'
        fileSize: 52857
        format: nexus
        name: e208341.nxs
        parameters:
        - dateTimeValue: '2012-07-16T16:12:08+02:00'
          type: lastaccess
      endDate: '2010-10-05T10:32:21+02:00'
      name: e208341
      parameters:
      - numericValue: 5.0
        type: reactor_power
      - numericValue: 2.7
        type: magnetic_field
      startDate: '2010-10-02T04:00:21+02:00'
      type: raw
    - complete: false
      datafiles: []
      endDate: '2010-10-12T17:00:00+02:00'
      name: e208342
      startDate: '2010-10-09T07:00:00+02:00'
      type: raw
    doi: DOI:00.0815/inv-00601
    endDate: '2010-10-12T17:00:00+02:00'
    facility: example_facility
    fundingReferences: []
    instrument: e2
    invcol: []
    invguest:
    - jbotu
    - jdoe
    - nbour
    invpi: ahau
    keywords:
    - NiMnGa
    - Nickel
    - Manganese
    - Gallium
    name: 10100601-ST
    parameters:
    - stringValue: neutron
      type: probe
    sample:
      name: NiMnGa 991027
      parameters:
      - stringValue: 2046c9a7-ab07-4594-84a2-101617073a79
        type: sample_ref
      pid: IGSN:ESNFZDVHICBD
      type: nimnga
    shifts:
    - comment: Beamtime at E2
      endDate: '2010-10-06T08:00:00+02:00'
      startDate: '2010-09-29T08:00:00+02:00'
    - comment: Beamtime at E2
      endDate: '2010-10-13T08:00:00+02:00'
      startDate: '2010-10-09T08:00:00+02:00'
    startDate: '2010-09-30T12:27:24+02:00'
    title: Ni-Mn-Ga flat cone
    type: experiment
    visitId: 1.1-N
  12100409-ST:
    datasets:
    - complete: false
      datafiles:
      - checksum: bd55affa
        datafileCreateTime: '2012-07-30T03:10:08+02:00'
        datafileModTime: '2012-07-30T03:10:08+02:00'
        fileSize: 459
        format: other
        name: e208945.dat
        parameters:
        - dateTimeValue: '2014-10-02T14:32:51+02:00'
          type: lastaccess
      - checksum: 1db15f18
        datafileCreateTime: '2013-06-03T12:22:43+02:00'
        datafileModTime: '2013-06-03T12:22:43+02:00'
        fileSize: 396430
        format: nexus
        name: e208945.nxs
        parameters:
        - dateTimeValue: '2014-10-02T14:32:51+02:00'
          type: lastaccess
      endDate: '2012-07-30T03:10:08+02:00'
      name: e208945
      parameters:
      - numericValue: 3.92
        type: sample_temperature_c
      - numericValue: 277.07
        type: sample_temperature_k
      startDate: '2012-07-26T17:44:24+02:00'
      type: raw
    - complete: false
      datafiles: []
      endDate: '2012-08-06T03:10:08+02:00'
      name: e208946
      startDate: '2012-08-02T07:30:00+02:00'
      type: raw
    doi: DOI:00.0815/inv-00409
    endDate: '2012-08-06T03:10:08+02:00'
    facility: example_facility
    fundingReferences:
    - fund1
    instrument: eddi
    invcol: []
    invguest:
    - rbeck
    invpi: nbour
    keywords:
    - NiO
    - Nickel oxide
    - Nickel
    - oxide
    name: 12100409-ST
    parameters:
    - stringValue: photon
      type: probe
    sample:
      name: Nickel(II) oxide SC
      parameters:
      - stringValue: c1b0a101-03aa-4d02-a1a2-e2826ba7871b
        type: sample_ref
      pid: IGSN:ESNFX8C7B53W
      type: nio
    shifts:
    - comment: Beamtime at EDDI
      endDate: '2012-08-07T06:00:00+02:00'
      startDate: '2012-07-24T06:00:00+02:00'
    startDate: '2012-07-26T17:44:24+02:00'
    title: NiO SC OF1 JUH HHL
    type: experiment
    visitId: 1.1-P
jobs:
  job1:
    application: gnomoanalytics
    input:
      datasets:
      - investigation: 10100601-ST
        name: e208341
      datafiles:
      - dataset: e208945
        investigation: 12100409-ST
        name: e208945.nxs
      parameters:
      - stringValue: Make a synthesis of 10100601-ST and 12100409-ST
        type: comment
    output:
      datasets:
      - complete: true
        datafiles:
        - datafileCreateTime: '2012-07-16T16:30:17+02:00'
          datafileModTime: '2012-07-16T16:30:17+02:00'
          fileSize: 14965
          format: nexus
          name: e208947.nxs
          parameters:
          - dateTimeValue: '2012-07-17T09:28:18+02:00'
            type: lastaccess
        endDate: '2012-07-16T16:30:17+02:00'
        investigation: 12100409-ST
        name: e208947
        startDate: '2012-07-16T13:42:05+02:00'
        type: analyzed
      datafiles:
      - datafileCreateTime: '2012-07-16T16:30:17+02:00'
        datafileModTime: '2012-07-16T16:30:17+02:00'
        dataset: e208945
        fileSize: 28937
        format: nexus
        investigation: 12100409-ST
        name: e208945-2.nxs
        parameters:
        - dateTimeValue: '2014-10-02T14:32:51+02:00'
          type: lastaccess
      doi: DOI:00.0815/dat-004711
parameter_types:
  comment:
    applicableToDataCollection: true
    applicableToDatafile: true
    applicableToDataset: true
    applicableToInvestigation: true
    applicableToSample: true
    facility: example_facility
    name: Comment
    units: N/A
    valueType: STRING
  lastaccess:
    applicableToDatafile: true
    applicableToDataset: true
    facility: example_facility
    name: Last access
    units: N/A
    valueType: DATE_AND_TIME
  magnetic_field:
    applicableToDataset: true
    facility: example_facility
    name: Magnetic field
    units: T
    unitsFullName: Tesla
    valueType: NUMERIC
  probe:
    applicableToDataset: true
    applicableToInvestigation: true
    facility: example_facility
    name: Probe
    units: N/A
    valueType: STRING
    values:
    - muon
    - neutron
    - photon
  reactor_power:
    applicableToDataset: true
    facility: example_facility
    name: Reactor power
    units: MW
    unitsFullName: Megawatt
    valueType: NUMERIC
  sample_ref:
    applicableToSample: true
    facility: example_facility
    name: Sample reference
    units: N/A
    valueType: STRING
  sample_temperature_c:
    applicableToDataset: true
    facility: example_facility
    name: Sample temperature
    units: C
    unitsFullName: Celsius
    valueType: NUMERIC
  sample_temperature_k:
    applicableToDataset: true
    facility: example_facility
    name: Sample temperature
    units: K
    unitsFullName: Kelvin
    valueType: NUMERIC
  scoundrel:
    applicableToInvestigation: true
    facility: example_facility
    name: Scoundrel
    units: N/A
    valueType: STRING
    values:
    - buono
    - brutto
    - cattivo
publications:
  pub1:
    investigation: 10100601-ST
    fullReference: >-
      A. Hau.  Properties of NiMnGa.  Adv. Mater. 2011, 1
    doi: DOI:00.1002/adma.201101001
related_datafiles:
  rdf1:
    dest:
      checksum: 7c72b4bc
      datafileCreateTime: '2010-10-05T11:31:53+02:00'
      datafileModTime: '2010-10-05T11:31:53+02:00'
      dataset: e208945
      fileSize: 52857
      format: nexus
      investigation: 12100409-ST
      name: e208341.nxs
      parameters:
      - dateTimeValue: '2014-10-02T14:32:51+02:00'
        type: lastaccess
    relation: copy
    source:
      dataset: e208341
      investigation: 10100601-ST
      name: e208341.nxs
sample_types:
  durol:
    facility: example_facility
    molecularFormula: C10H14
    name: Durol SC
  nimnga:
    facility: example_facility
    molecularFormula: NiMnGa
    name: NiMnGa
  nio:
    facility: example_facility
    molecularFormula: NiO
    name: Nickel(II) oxide SC
studies:
  study1:
    endDate: '2012-09-30T20:00:00+02:00'
    investigations:
    - 10100601-ST
    - 12100409-ST
    name: 12-008
    pid: DOI:00.0815/m-00333
    startDate: '2012-07-09T08:00:00+02:00'
    status: COMPLETE
    user: nbour
techniques:
  arpes:
    name: Angle Resolved Photoemission Spectroscopy
    description: Angle Resolved Photoemission Spectroscopy
    pid: PaNET:PaNET01089
  haxpes:
    name: Hard X-ray Photoelectron Spectroscopy
    description: Hard X-ray Photoelectron Spectroscopy
    pid: PaNET:PaNET01103
  ndiff:
    name: Neutron Diffraction
    description: Neutron Diffraction
    pid: PaNET:PaNET01217
  xtomo:
    name: X-ray Tomography
    description: X-ray Tomography
    pid: PaNET:PaNET01207
users:
  acord:
    affiliation: University of Ravenna, Institute of Modern History
    email: acord@example.org
    familyName: Cordus
    fullName: Aelius Cordus
    givenName: Aelius
    name: db/acord
    orcidId: 0000-0002-3262
  ahau:
    affiliation: Goethe University Frankfurt, Faculty of Philosophy and History
    email: ahau@example.org
    familyName: Hau
    fullName: Arnold Hau
    givenName: Arnold
    name: db/ahau
    orcidId: 0000-0002-3263
  jbotu:
    affiliation: "Universit\xE9 Paul-Val\xE9ry Montpellier 3"
    email: jbotu@example.org
    familyName: Botul
    fullName: Jean-Baptiste Botul
    givenName: Jean-Baptiste
    name: db/jbotu
    orcidId: 0000-0002-3264
  jdoe:
    email: jdoe@example.org
    familyName: Doe
    fullName: John Doe
    givenName: John
    name: db/jdoe
  nbour:
    affiliation: University of Nancago
    email: nbour@example.org
    familyName: Bourbaki
    fullName: Nicolas Bourbaki
    givenName: Nicolas
    name: db/nbour
    orcidId: 0000-0002-3266
  rbeck:
    affiliation: "Kaiser-Wilhelms-Akademie f\xFCr das milit\xE4r\xE4rztliche Bildungswesen"
    email: rbeck@example.org
    familyName: "Beck-D\xFClmen"
    fullName: "Rudolph Beck-D\xFClmen"
    givenName: Rudolph
    name: db/rbeck
    orcidId: 0000-0002-3267
