# -*- coding: utf-8 -*-
#
# python-icat documentation build configuration file.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

import os
from pathlib import Path
import sys

docsrcdir = Path(__file__).resolve().parent
maindir = docsrcdir.parent.parent
buildlib = maindir / "build" / "lib"
sys.path[0] = str(buildlib)
sys.dont_write_bytecode = True

import icat._meta

# -- Project information -----------------------------------------------------

project = 'python-icat'
copyright = ('2013–2025, '
             'Helmholtz-Zentrum Berlin für Materialien und Energie GmbH')
author = 'Rolf Krahl'

# The full version, including alpha/beta/rc tags
release = icat._meta.version
# The short X.Y version
version = ".".join(release.split(".")[0:2])

# Write a _meta.rst that defines some custom substitutions
def make_meta_rst(last_release):
    template = """:orphan:

.. |distribution_source| replace:: %(dist_src_name)s
.. |distribution_signature| replace:: %(dist_sig_name)s
.. _distribution_source: %(dist_src_url)s
.. _distribution_signature: %(dist_sig_url)s
"""
    github_repo = "https://github.com/icatproject/python-icat"
    dist_src_name = "python-icat-%s.tar.gz" % last_release
    dist_src_url = ("%s/releases/download/%s/%s"
                    % (github_repo, last_release, dist_src_name))
    dist_sig_name = "python-icat-%s.tar.gz.asc" % last_release
    dist_sig_url = ("%s/releases/download/%s/%s"
                    % (github_repo, last_release, dist_sig_name))
    subst = {
        'dist_src_name': dist_src_name,
        'dist_src_url': dist_src_url,
        'dist_sig_name': dist_sig_name,
        'dist_sig_url': dist_sig_url,
    }
    with (docsrcdir / '_meta.rst').open('wt') as f:
        print(template % subst, file=f)

make_meta_rst(icat._meta.release)

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = '1.8'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
]
try:
    import sphinx_copybutton
    extensions.append('sphinx_copybutton')
except ImportError:
    pass

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# Enable automatic numbering of figures, tables and code-blocks
numfig = True

# Strings to format figure, table, code-block, and section numbers
numfig_format = {
    'figure': "Figure %s",
    'table': "Table %s",
    'code-block': "Snippet %s",
    'section': "Section %s",
}

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for autodoc extension -------------------------------------------

autodoc_member_order = 'bysource'

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'lxml': ('https://lxml.de/apidoc/', None),
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Define the canonical URL if you are using a custom domain on Read the Docs
html_baseurl = os.environ.get("READTHEDOCS_CANONICAL_URL", "")

# Tell Jinja2 templates the build is running on Read the Docs
if os.environ.get("READTHEDOCS", "") == "True":
    if "html_context" not in globals():
        html_context = {}
    html_context["READTHEDOCS"] = True

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

html_favicon = "images/favicon-32x32.png"

html_css_files = [
    'css/captions.css',
    'css/spacing.css',
]


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = '%s-doc' % project


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, '%s.tex' % project, '%s Documentation' % project,
     author, 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('icatdump', 'icatdump',
     'Dump the content of the ICAT to a file',
     [author], 1),
    ('icatingest', 'icatingest',
     'Restore the content of the ICAT from a dump file',
     [author], 1),
    ('wipeicat', 'wipeicat',
     'Delete all content from an ICAT',
     [author], 1),
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, project, '%s Documentation' % project,
     author, project, 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------
