name: Check ReST input files
on:
  push:
    branches:
      - develop
      - master
  pull_request:
jobs:
  doc8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install setuptools packaging git-props suds
      - name: Run conf.py
        run: |
          python setup.py build
          python doc/src/conf.py
      - name: doc8-check
        uses: deep-entertainment/doc8-action@v4
        with:
          scanPaths: "doc/src"
